services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    command: ["--config=/etc/otel-collector.yml"]
    volumes:
      - ./otel-collector.yml:/etc/otel-collector.yml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
      - "9464:9464" # Prometheus metrics
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    depends_on:
      - otel-collector
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - otel-collector
    networks:
      - monitoring

  # tempo:
  #   image: grafana/tempo
  #   container_name: tempo
  #   command: ["-config.file=/etc/tempo.yml"]
  #   volumes:
  #     - ./tempo.yml:/etc/tempo.yml
  #   depends_on:
  #     - otel-collector
  #   networks:
  #     - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ORG_NAME=passman
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "4000:3000"
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
    external: true
