global:
  scrape_interval: 5s # Adjust as needed

scrape_configs:
  # Scrape metrics from the OpenTelemetry Collector
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"] # Collects metrics from OTel Collector
