name: Deploy Grafana LGTM stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Create Docker context and set in use
        run: |
          ssh-keyscan -H passman.live >> ~/.ssh/known_hosts
          docker context create passman --docker "host=ssh://ec2-user@passman.live"
          docker context use passman
          # Check if the secret already exists
          if ! docker secret ls --filter name=grafana_password -q; then
            echo "Secret does not exist. Creating Docker secret..."
            echo "$${{ secrets.GRAFANA_ADMIN_PASSWORD }}" | docker secret create grafana_password -
          else
            echo "Secret already exists."
          fi

          # remove configs first
          # docker config rm grafana_otel_config
          # docker config rm grafana_tempo_config
          # docker config rm grafana_prometheus_config
          # docker config rm grafana_loki_config

      - name: Docker stack deploy
        run: |
          docker stack config -c docker-stack.yml | docker stack deploy -c - grafana -d --with-registry-auth
